<?php

/**
 * @file
 * API and module for Salesforce integration.
 */

define('SALESFORCE_DEFAULT_ENDPOINT', 'https://login.salesforce.com');

module_load_include('inc', 'salesforce', 'includes/salesforce');

/**
 * Implements hook_config_info().
 */
function salesforce_config_info() {
  $prefixes['salesforce.settings'] = [
    'label' => t('Salesforce API settings'),
    'group' => t('Configuration'),
  ];
  $prefixes['salesforce.auth_settings'] = [
    'label' => t('Salesforce Auth settings'),
    'group' => t('Configuration'),
  ];
  return $prefixes;
}

/**
 * Implements hook_menu().
 */
function salesforce_menu() {
  $items = [];

  $items['admin/config/salesforce'] = [
    'title' => 'Salesforce',
    'description' => 'Salesforce settings.',
    'position' => 'right',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => ['access administration pages'],
    'file path' => backdrop_get_path('module', 'system'),
    'file' => 'system.admin.inc',
  ];
  $items['admin/config/salesforce/authorize'] = [
    'title' => 'Authorize',
    'description' => 'Authorize this website to communicate with Salesforce.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['salesforce_oauth_form'],
    'access arguments' => ['administer salesforce'],
    'type' => MENU_NORMAL_ITEM,
    'weight' => 0,
  ];
  $items['admin/config/salesforce/settings'] = [
    'title' => 'Settings',
    'description' => 'Additional settings for the Salesforce Suite.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => ['salesforce_settings_form'],
    'access arguments' => ['administer salesforce'],
    'type' => MENU_NORMAL_ITEM,
    'weight' => 1,
  ];
  $items['salesforce/oauth_callback'] = [
    'title' => 'Salesforce oauth callback',
    'page callback' => 'salesforce_oauth_callback',
    'access arguments' => ['administer salesforce'],
    'type' => MENU_CALLBACK,
  ];

  $items['admin/structure/salesforce'] = [
    'title' => 'Salesforce',
    'description' => 'Configuration for Salesforce integration.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => ['administer salesforce'],
    'file' => 'system.admin.inc',
    'file path' => backdrop_get_path('module', 'system'),
  ];

  return $items;
}

/**
 * Implements hook_permission().
 */
function salesforce_permission() {
  return [
    'administer salesforce' => [
      'title' => t('administer salesforce'),
      'description' => t('Administer Salesforce integration.'),
      'restrict access' => TRUE,
    ],
  ];
}

/**
 * Implements hook_flush_caches().
 */
function salesforce_flush_caches() {
  return ['cache_salesforce_object'];
}

/**
 * Generate the Salesforce authorization form.
 *
 * @return array
 *   The Salesforce authorization form.
 */
function salesforce_oauth_form() {
  $config = config('salesforce.settings');
  // Overlay doesn't work. See https://www.drupal.org/node/2268401.
  if (module_exists('overlay') && overlay_get_mode() == 'child') {
    $current_path = current_path();
    overlay_close_dialog($current_path);
  }
  $form = [];

  $consumer_key = $config->get('salesforce_consumer_key');
  $salesforce_endpoint = $config->get('salesforce_endpoint');
  try {
    $consumer_secret = salesforce_get_consumer_secret();
  }
  catch (CantLoadSalesforceConsumerSecret $e) {
    $form['message'] = [
      '#type' => 'warning',
      '#markup' => t($e->getMessage()),
    ];
  }

  $form['message'] = [
    '#type' => 'item',
    '#markup' => t('Authorize this website to communicate with Salesforce by entering the consumer key and secret from a remote application. Clicking authorize will redirect you to Salesforce where you will be asked to grant access.'),
  ];

  $form['salesforce_consumer_key'] = [
    '#title' => t('Salesforce consumer key'),
    '#type' => 'textfield',
    '#description' => t('Consumer key of the Salesforce remote application you want to grant access to'),
    '#required' => TRUE,
    '#default_value' => $consumer_key,
  ];
  $form['advanced'] = [
    '#title' => t('Advanced'),
    '#type' => 'fieldset',
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  ];
  $form['advanced']['salesforce_endpoint'] = [
    '#title' => t('Salesforce endpoint'),
    '#type' => 'textfield',
    '#description' => t('Enter the URL of your Salesforce environment (for example, <code>https://test.salesforce.com</code>). <strong>Caution:</strong> Note that switching this setting after you have already synchronised data between your Backdrop site and Salesforce will render any existing links between Salesforce objects and Backdrop objects invalid!'),
    '#default_value' => $salesforce_endpoint,
  ];
  $form['submit'] = [
    '#value' => t('Authorize'),
    '#type' => 'submit',
  ];

  // If we're authenticated, show a list of available REST resources.
  if ($consumer_key && $consumer_secret) {
    $sfapi = new Salesforce($consumer_key, $consumer_secret);
    // If fully configured, attempt to connect to Salesforce and return a list
    // of resources.

    if ($sfapi->isAuthorized()) {
      try {
        $resources = $sfapi->listResources();
        foreach ($resources as $key => $path) {
          $items[] = $key . ': ' . $path;
        }
        $form['resources'] = [
          '#title' => t('Your Salesforce instance is authorized and has access to the following resources:'),
          '#type' => 'item',
          '#markup' => theme('item_list', ['items' => $items]),
        ];
      } catch (SalesforceException $e) {
        salesforce_set_message(t('Salesforce Exception during @event : @exception', [
          '@event' => 'oauth',
          '@exception' => $e->getMessage(),
        ]), 'warning');
      }
    }
    else {
      salesforce_set_message(t('Salesforce needs to be authorized to connect to this website.'), 'error');
    }
  }

  return $form;
}

/**
 * Submit handler for salesforce_oauth_form().
 *
 * @param array $form
 *   The form array.
 * @param array $form_state
 *   The form state array.
 */
function salesforce_oauth_form_submit($form, &$form_state) {
  $consumer_key = $form_state['values']['salesforce_consumer_key'];
  $consumer_secret = salesforce_get_consumer_secret();
  $salesforce_endpoint = empty($form_state['values']['salesforce_endpoint']) ? SALESFORCE_DEFAULT_ENDPOINT : $form_state['values']['salesforce_endpoint'];
  config_set('salesforce.settings', 'salesforce_consumer_key', $consumer_key);
  config_set('salesforce.settings', 'salesforce_endpoint', $salesforce_endpoint);

  $salesforce = new Salesforce($consumer_key, $consumer_secret);
  $salesforce->getAuthorizationCode();
}

/**
 * Generate the Salesforce settings form.
 */
function salesforce_settings_form($form, &$form_state) {
  // Get the default or current setting.
  $config = config('salesforce.settings');
  $api_version = $config->get('salesforce_api_version');
  if ($api_version == "" || empty($api_version)) {
    $api_version = [
      "label" => "Summer '14",
      "url" => "/services/data/v31.0",
      "version" => "31.0",
    ];
  }
  $api_list = [$api_version];

  // If we're authenticated, get the full list of available versions.
  $salesforce = salesforce_get_api();
  $instance = $salesforce->getInstanceUrl();

  if ($instance) {
    // Get all available API versions.
    $api_list = backdrop_http_request($instance . "/services/data");
    $api_list = backdrop_json_decode($api_list->data);
  }
  // Store api list for use in our validate callback.
  $form_state['api_list'] = $api_list;

  // Build the options array.
  $options = [];
  foreach ($api_list as $api) {
    $options[$api['version']] = $api['label'] . ' (' . $api['version'] . ')';
  }

  $form['salesforce_api_version'] = [
    '#type' => 'select',
    '#title' => t('API Version'),
    '#description' => t('Select the version of the Salesforce API to use'),
    '#default_value' => $api_version['version'],
    '#options' => $options,
  ];

  $form['#validate'][] = 'salesforce_settings_form_validate';
  $form['#submit'][] = 'salesforce_settings_form_submit';
  $form['actions']['#type'] = 'actions';
  $form['actions']['submit'] = [
    '#type' => 'submit',
    '#value' => t('Save configuration')
  ];

  return $form;
}

/**
 * Validation handler for salesforce_settings_form().
 */
function salesforce_settings_form_validate($form, &$form_state) {
  // Convert version to the array of api info.
  $version = $form_state['values']['salesforce_api_version'];
  if ($version) {
    // Loop through available api versions to find a match.
    foreach ($form_state['api_list'] as $api) {
      if ($api['version'] == $version) {
        form_set_value($form['salesforce_api_version'], $api, $form_state);
        break;
      }
    }
  }
}

/**
 * Submit handler for salesforce_settings_form().
 */
function salesforce_settings_form_submit($form, &$form_state) {
  config_set('salesforce.settings', 'salesforce_api_version', $form_state['values']['salesforce_api_version']);
}

/**
 * Callback for the oauth redirect URI.
 *
 * Exchanges an authorization code for an access token.
 */
function salesforce_oauth_callback() {
  // If no code is provided, return access denied.
  if (!isset($_GET['code'])) {
    return backdrop_access_denied();
  }
  if (!isset($_GET['state']) || !backdrop_valid_token($_GET['state'], 'salesforce_oauth')) {
    return backdrop_access_denied();
  }
  $salesforce = salesforce_get_api();
  if ($salesforce->requestToken($_GET['code'])) {
    salesforce_set_message(t('Salesforce OAUTH2 authorization successful.'));

    // Rebuild the menu so the mappings links are now available.
    menu_rebuild();
  }
  else {
    salesforce_set_message(t('Salesforce OAUTH2 authorization failed, likely due to inadequate OAUTH scope. Ensure your app has scope %scope selected.', ['%scope' => 'Perform requests on your behalf at any time']), 'warning');
  }

  backdrop_goto('admin/config/salesforce/authorize');
}

/**
 * Wrapper around the API constructor passing consume key and secret.
 *
 * @return Salesforce
 *   Returns a Salesforce class object.
 */
function salesforce_get_api() {
  $config = config('salesforce.settings');
  $consumer_secret = salesforce_get_consumer_secret();
  return new Salesforce(
    $config->get('salesforce_consumer_key'),
    $consumer_secret
  );
}

function salesforce_get_consumer_secret() {
  $config = config('salesforce.settings');
  $secret_path = $config->get('salesforce_consumer_secret_path') . '/salesforce_consumer_secret.json';
  if (file_exists($secret_path)) {
    if (is_readable($secret_path)) {
      $file = file_get_contents($secret_path);
      $json = json_decode($file);
      if ($json && property_exists($json, 'salesforce_consumer_secret')) {
        return $json->salesforce_consumer_secret;
      }
      else {
        throw new \CantLoadSalesforceConsumerSecret(t('salesforce_consumer_secret file at ' . $secret_path . ' is malformed.'));
      }
    }
    else {
      throw new \CantLoadSalesforceConsumerSecret(t('salesforce_consumer_secret file at ' . $secret_path . ' exists, but is not readable.'));
    }
  }
  else {
    throw new \CantLoadSalesforceConsumerSecret(t('No salesforce_consumer_secret file at ' . $secret_path));
  }
}

/**
 * Salesforce set message.
 *
 * Wrapper around backdrop_set_message(), adding check for administer
 * salesforce
 * permission.
 *
 * @param string $message
 *   (optional) The translated message to be displayed to the user.
 * @param string $type
 *   (optional) The message's type. Defaults to 'status'.
 * @param bool $repeat
 *   (optional) If this is FALSE and the message is already set, then the
 *   message won't be repeated. Defaults to TRUE.
 *
 * @return array|null
 *   results of backdrop_set_message(), if current user has permissions, or
 *   null.
 *
 * @see backdrop_set_message()
 */
function salesforce_set_message($message = NULL, $type = 'status', $repeat = TRUE) {
  global $user;
  if ($user->uid == 1 || user_access('administer salesforce', $user)) {
    return backdrop_set_message($message, $type, $repeat);
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function salesforce_ctools_plugin_directory($module, $plugin_type) {
  if ($module == 'addressfield') {
    return 'plugins/addressfield/' . $plugin_type;
  }
}

/**
 * Implements hook_autoload_info().
 */
function salesforce_autoload_info() {
  return [
    'Salesforce' => 'includes/salesforce.inc',
    'SalesforceException' => 'includes/salesforce.inc',
    'SalesforcePullException' => 'includes/salesforce.inc',
    'SalesforceSelectQuery' => 'includes/salesforce.select_query.inc',
  ];
}
